AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1
